; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Morning Star Cooperative"
#define MyAppVersion "1.5"
#define MyAppPublisher "morning star "
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "morning_star_cooperative.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{AE50C004-37AE-44C1-A0CB-79262B4DED96}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\Morning_Star_Cooperative
DisableDirPage=yes
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputBaseFilename=mysetup
SetupIconFile=C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\app\assets\icon.ico
SolidCompression=yes
WizardStyle=modern dark

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\data\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\DLLs\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\Lib\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\site-packages\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\battery_plus_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\connectivity_plus_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\morning_star_cooperative.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\msvcp140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\python3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\python312.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\screen_brightness_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\screen_retriever_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\serious_python_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\share_plus_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\url_launcher_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\vcruntime140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\vcruntime140_1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HP\Documents\flet_projects\LMS-PYTHON-FLET\build\windows\window_manager_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

